title: Guillaume Vaval # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters of Science in Business Analytics Graduate from UVA Darden & McIntire
  <br><br>
  Certified Public Accountant at the intersection of business and data 
  <br><br>
  <a href="https://www.linkedin.com/in/gvaval/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
